apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: offline-pep
  description: offline-pep
  tags:
  - go
  - vue
  - javascript
  - makefile
  - shell
  - dockerfile
  - batchfile
  - scss
spec:
  type: unknown
  owner: group:possible-orphan
  lifecycle: unknown